"""Odyssey's Python application and domain core."""

from .context import (
    ContextIndex,
    ContextIndexError,
    ContextItem,
    ContextPackage,
    ContextRetrievalError,
    build_context_retrieval_text,
    get_context,
)
from .identity import (
    ExactEntityCandidate,
    ExactEntityLookupError,
    ExactEntityResolution,
    ExactResolutionOutcome,
    MatchKind,
    find_exact_entity_candidates,
    resolve_exact_entity,
)
from .persistence import (
    EntityAlreadyExistsError,
    EntityIdentityMismatchError,
    EntityPersistenceResult,
    PersistenceOperation,
    ProtectedMetadataError,
    create_entity,
    update_entity,
)
from .resolution import (
    ExistingEntityOutcome,
    ExistingEntityResolution,
    ExistingEntityResolutionError,
    ResolutionSource,
    build_provider_evidence,
    resolve_existing_entity,
)
from .semantic import (
    DEFAULT_EMBEDDING_MODEL,
    FastEmbedTextEmbedder,
    SemanticEntityCandidate,
    SemanticEntityIndex,
    SemanticIndexError,
    TextEmbedder,
    build_semantic_retrieval_text,
    find_semantic_entity_candidates,
)

__all__ = [
    "ExactEntityCandidate",
    "ExactEntityLookupError",
    "ExactEntityResolution",
    "ExactResolutionOutcome",
    "MatchKind",
    "find_exact_entity_candidates",
    "resolve_exact_entity",
    "DEFAULT_EMBEDDING_MODEL",
    "FastEmbedTextEmbedder",
    "SemanticEntityCandidate",
    "SemanticEntityIndex",
    "SemanticIndexError",
    "TextEmbedder",
    "build_semantic_retrieval_text",
    "find_semantic_entity_candidates",
    "ContextIndex",
    "ContextIndexError",
    "ContextItem",
    "ContextPackage",
    "ContextRetrievalError",
    "build_context_retrieval_text",
    "get_context",
    "ExistingEntityOutcome",
    "ExistingEntityResolution",
    "ExistingEntityResolutionError",
    "ResolutionSource",
    "build_provider_evidence",
    "resolve_existing_entity",
    "EntityAlreadyExistsError",
    "EntityIdentityMismatchError",
    "EntityPersistenceResult",
    "PersistenceOperation",
    "ProtectedMetadataError",
    "create_entity",
    "update_entity",
]
